name: Services
items:
    -
        title: 'Contact us'
        type: url
        url: /
        code: ''
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
    -
        title: Refund
        type: url
        url: /
        code: ''
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
    -
        title: Sitemap
        type: url
        url: /
        code: ''
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
    -
        title: Sales
        type: url
        url: /
        code: ''
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
